// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjectEstimator.Api.Data;

namespace ProjectEstimator.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20200331231904_InitialRateProfiles")]
    partial class InitialRateProfiles
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ProjectEstimator.Api.Models.RateProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<int>("BuildingPlumbing")
                        .HasColumnType("int");

                    b.Property<int>("CoreExteriorDoors")
                        .HasColumnType("int");

                    b.Property<int>("CoreInteriorDoors")
                        .HasColumnType("int");

                    b.Property<int>("CoreLobbyMain")
                        .HasColumnType("int");

                    b.Property<int>("CoreLobbyUpper")
                        .HasColumnType("int");

                    b.Property<int>("CoreRestroom")
                        .HasColumnType("int");

                    b.Property<int>("CoreVestibules")
                        .HasColumnType("int");

                    b.Property<int>("CurtainWallSystem")
                        .HasColumnType("int");

                    b.Property<double>("DesignEng")
                        .HasColumnType("float");

                    b.Property<int>("ElecServ")
                        .HasColumnType("int");

                    b.Property<int>("ElevatorPitConcrete")
                        .HasColumnType("int");

                    b.Property<int>("ElevatorShaftWalls")
                        .HasColumnType("int");

                    b.Property<int>("EntryCanopyRoof")
                        .HasColumnType("int");

                    b.Property<int>("EntryCanopySteel")
                        .HasColumnType("int");

                    b.Property<double>("FireAlarm")
                        .HasColumnType("float");

                    b.Property<double>("FireProtectionSystems")
                        .HasColumnType("float");

                    b.Property<int>("FireProtectionSystemsUnderCanopies")
                        .HasColumnType("int");

                    b.Property<double>("HvacDesign")
                        .HasColumnType("float");

                    b.Property<int>("HydraulicElevator")
                        .HasColumnType("int");

                    b.Property<int>("JanitorClosetPlumbing")
                        .HasColumnType("int");

                    b.Property<int>("JanitorClosets")
                        .HasColumnType("int");

                    b.Property<double>("MechScreen")
                        .HasColumnType("float");

                    b.Property<int>("MepRooms")
                        .HasColumnType("int");

                    b.Property<int>("MepShaftWalls")
                        .HasColumnType("int");

                    b.Property<double>("MiscExteriorWindowAndWallFlashings")
                        .HasColumnType("float");

                    b.Property<int>("MiscellaneousSteel")
                        .HasColumnType("int");

                    b.Property<int>("RestroomPlumbingFixtures")
                        .HasColumnType("int");

                    b.Property<double>("RoofRelatedSheetMetals")
                        .HasColumnType("float");

                    b.Property<double>("RoughCarpentry")
                        .HasColumnType("float");

                    b.Property<double>("ScPaint")
                        .HasColumnType("float");

                    b.Property<int>("Skylights")
                        .HasColumnType("int");

                    b.Property<double>("SlabPrep")
                        .HasColumnType("float");

                    b.Property<int>("StairWellWalls")
                        .HasColumnType("int");

                    b.Property<int>("StorefrontWindowSystems")
                        .HasColumnType("int");

                    b.Property<double>("StructuralExcav")
                        .HasColumnType("float");

                    b.Property<int>("UpgradeElevatorCabFinish")
                        .HasColumnType("int");

                    b.Property<int>("WaterBelGradeWall")
                        .HasColumnType("int");

                    b.Property<int>("WaterproofElevatorPit")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("RateProfiles");
                });
#pragma warning restore 612, 618
        }
    }
}
